apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-delivery-ingress
spec:
  rules:
    - host: food.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: food-delivery-service
                port:
                  number: 80
